---
deployment:
  tasks:
    - export DEPLOYPATH=/home/theseu6/undergroundfolkcollective.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp upcoming.html $DEPLOYPATH
    - /bin/cp gallery_photos.html $DEPLOYPATH
    - /bin/cp gallery_videos.html $DEPLOYPATH
    - /bin/cp gallery_audio.html $DEPLOYPATH